services:
   # MySQL 8.0
   mysql:
      image: mysql:8.0
      container_name: vocab_vault_mysql
      restart: unless-stopped
      environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
         MYSQL_DATABASE: vocab_vault
         MYSQL_USER: ${MYSQL_USER:-root}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      volumes:
         - mysql_data:/var/lib/mysql
      ports:
         - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password --sql_mode=""
      networks:
         - vocab_vault_network

   # Backend - API server
   backend:
      image: pezoi/vocab-vault-backend:latest
      container_name: vocab_vault_backend
      restart: unless-stopped
      environment:
         SPRING_PROFILES_ACTIVE: docker
         DBMS_URL: mysql://mysql:3306/vocab_vault
         DBMS_USERNAME: ${MYSQL_USER:-root}
         DBMS_PASSWORD: ${MYSQL_PASSWORD:-root}
         EMAIL: ${EMAIL}
         PASSWORD_EMAIL: ${PASSWORD_EMAIL}
         GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
         GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
         GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL:-https://vocab-vault.site/google/callback}
         CLOUD_NAME: ${CLOUD_NAME}
         CLOUD_API_KEY: ${CLOUD_API_KEY}
         CLOUD_API_SECRET: ${CLOUD_API_SECRET}
         JWT_KEY_SECRET: ${JWT_KEY_SECRET}
         GEMINI_API_KEY: ${GEMINI_API_KEY}
         JAVA_OPTS: "-Xms128m -Xmx400m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
         VOCAB_VAULT_DOMAIN_FRONTEND: ${FRONTEND_URL:-https://vocab-vault.site}
      # Backend không expose port ra ngoài, chỉ thông qua Nginx
      expose:
         - "8080"
      depends_on:
         - mysql
      networks:
         - vocab_vault_network

   # Frontend - Vite React app
   frontend:
      image: pezoi/vocab-vault-frontend:latest
      container_name: vocab_vault_frontend
      restart: unless-stopped
      # Frontend không expose port ra ngoài, chỉ thông qua Nginx
      expose:
         - "80"
      depends_on:
         - backend
      networks:
         - vocab_vault_network

   # Nginx Reverse Proxy - Điều hướng traffic
   nginx:
      image: nginx:alpine
      container_name: vocab_vault_nginx
      restart: unless-stopped
      ports:
         - "0.0.0.0:80:80" # Frontend access
         - "0.0.0.0:8080:8080" # Backend API access
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
         - ./nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf:ro
         - ./nginx/cert:/etc/nginx/cert:ro
      depends_on:
         - frontend
         - backend
      networks:
         - vocab_vault_network

volumes:
   mysql_data:
      driver: local

networks:
   vocab_vault_network:
      driver: bridge
